version: "3"

services:
  win-builder:
    container_name: win-builder
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ELECTRON_CACHE: "/root/.cache/electron"
      ELECTRON_BUILDER_CACHE: "/root/.cache/electron-builder"
      HTTP_PROXY: $${http_proxy}
      HTTPS_PROXY: $${https_proxy}
    volumes:
      - ./:/project
      - ./dist:/dist
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron-builder:/root/.cache/electron-builder
